version: '3.2'

services:
  
  rabbitmq:
    image: rabbitmq
    ports:
      - '5670:5670'
      - '5671:5671'
  
  producer:
    build: producer
    volumes:
      - ./producer:/app
    environment:
      - PYTHONUNBUFFERED=1
  
  ride_matching_consumer:
    build: ride_matching_consumer
    volumes:
      - ./ride_matching_consumer:/app
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
    environment:
      - PORTADDR=0.0.0.0:5000
      - CONSUMER_ID=1

  ride_matching_consumer2:
    build: ride_matching_consumer2
    volumes:
      - ./ride_matching_consumer2:/app
    ports:
      - 7000:7000
    depends_on:
      - rabbitmq
    environment:
      - SERVERIP=1.2.3.4
      - CONSUMERID=1428
  
  database_consumer:
    build: database_consumer
    volumes:
      - ./database_consumer:/app
    ports:
      - 6000:6000
    depends_on:
      - rabbitmq
      - mongodb
  
  mongodb:
    image: mongo
    expose:
      - 5187
